"""
This script excepts a csv file filled with n prime numbers
called res/primes.csv and generates a c header file which contains a const int
array with said frimes as well as a macro that contains
the number of primes in the array.


"""
import sys
if __name__ == "__main__":
    incsv = "res/primes.csv"
    out_h = "src/_primes.h"
    try:
        with open(incsv, "r") as f_in:
            primes = f_in.readlines()
            n_primes = len(primes)
            with open(out_h, "w") as f_out:
                f_out.write("#pragma once\n")
                f_out.write("// THIS FILE IS AUTOMATICALLY GENERATED DO NOT EDIT\n")
                f_out.write("#include <stddef.h>\n")
                f_out.write("const unsigned int PRIMES[]={\n")
                for prime in primes:
                    f_out.write(prime.strip()+",\n")
                f_out.write("};\n")
                f_out.write("const size_t N_PRIMES = sizeof(PRIMES) / sizeof(PRIMES[0]);\n")
    except Exception as e:
        print(e)
        sys.exit(1)
    sys.exit(0)